os: unstable
clone_script:
- ps: "if(-not $env:appveyor_pull_request_number) {\n      git clone --depth=1 -q -c filter.lfs.smudge= -c filter.lfs.required=false --branch=$env:appveyor_repo_branch git@github.com:$env:appveyor_repo_name.git $env:appveyor_build_folder\n      git checkout -qf $env:appveyor_repo_commit\n      git lfs pull\n    } else {\n      git clone --depth=1 -q -c filter.lfs.smudge= -c filter.lfs.required=false git@github.com:$env:appveyor_repo_name.git $env:appveyor_build_folder\n      git fetch -q origin +refs/pull/$env:appveyor_pull_request_number/merge:\n      git checkout -qf FETCH_HEAD\n      git lfs pull \n    }"
hosts:
  GitHub: 192.30.253.113
platform:
    - x64
init:
    - git config --global core.autocrlf input
cache:
    - node_modules
    - app\node_modules
    - '%APPDATA%\npm-cache'
    - '%USERPROFILE%\.electron'
environment:
    GH_TOKEN:
        secure: bXpDrAdIegR4vXueea1h+atdZdkZj1WzyjAt8geQmgQhQxk2QD92Dcu4z+5wXS9f
    matrix:
        - nodejs_version: 6
install:
    - ps: Install-Product node $env:nodejs_version
    - set CI=true
    - npm install -g npm@latest
    - set PATH=%APPDATA%\npm;%PATH%
    - npm install electron-builder
    - npm install gulp-cli -g
    - npm install
    - npm prune
matrix:
    fast_finish: true
test: off
shallow_clone: true
clone_depth: 1
build_script:
    - gulp build
    - npm run build
